name: Build KuaiYanGo2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout 后端仓库
    - name: Checkout KuaiYanGo2
      uses: actions/checkout@v4
      with:
        repository: wenfxl/KuaiYanGo2
        path: KuaiYanGo2

    # 2. Checkout 前端仓库
    - name: Checkout KuaiYanWeb
      uses: actions/checkout@v4
      with:
        repository: wenfxl/KuaiYanWeb
        path: KuaiYanWeb

    # 3. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # 4. Build KuaiYanWeb (Vue3)
    - name: Build KuaiYanWeb
      working-directory: KuaiYanWeb
      run: |
        npm install
        npm run build --ignore-scripts

    # 5. Copy 前端打包结果到后端 assets 目录
    - name: Copy front-end build to backend
      run: |
        mkdir -p KuaiYanGo2/core/dist
        cp -r KuaiYanWeb/dist/* KuaiYanGo2/core/dist/

    # 6. Setup Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    # 7. Go mod tidy (确保 replace ./utils 生效)
    - name: Go mod tidy
      working-directory: KuaiYanGo2
      run: go mod tidy

    # 8. Build Go binary
    - name: Build KuaiYanGo2
      working-directory: KuaiYanGo2
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o KuaiYanGo2.bin main.go

    # 9. Upload Go binary
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: KuaiYanGo2-bin
        path: KuaiYanGo2/KuaiYanGo2.bin
