name: Build KuaiYanGo2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout 后端仓库
    - name: Checkout KuaiYanGo2
      uses: actions/checkout@v4
      with:
        repository: wenfxl/KuaiYanGo2
        path: KuaiYanGo2

    # 2. Checkout 前端仓库
    - name: Checkout KuaiYanWeb
      uses: actions/checkout@v4
      with:
        repository: wenfxl/KuaiYanWeb
        path: KuaiYanWeb

    # 3. Setup Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    # 4. Build front-end assets (可选)
    - name: Build KuaiYanWeb (Vue3)
      working-directory: KuaiYanWeb
      run: |
        npm install
        npm run build
      env:
        CI: true

    # 5. Copy 前端打包资源到后端 assets 目录
    - name: Copy assets to backend
      run: |
        mkdir -p KuaiYanGo2/core/dist/VueAdmin
        mkdir -p KuaiYanGo2/core/dist/VueAgent
        cp -r KuaiYanWeb/dist/VueAdmin/* KuaiYanGo2/core/dist/VueAdmin/
        cp -r KuaiYanWeb/dist/VueAgent/* KuaiYanGo2/core/dist/VueAgent/

    # 6. Set replace for local utils
    - name: Ensure go.mod replace
      run: |
        cd KuaiYanGo2
        go mod tidy

    # 7. Build Go binary
    - name: Build KuaiYanGo2
      working-directory: KuaiYanGo2
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o KuaiYanGo2.bin main.go

    # 8. Upload artifact
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: KuaiYanGo2-bin
        path: KuaiYanGo2/KuaiYanGo2.bin
