name: Build KuaiYan BIN

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout 后端仓库（当前仓库 KuaiYanGo2）
    - name: Checkout Backend
      uses: actions/checkout@v3

    # Checkout 前端仓库 KuaiYanWeb 到子目录
    - name: Checkout Frontend
      uses: actions/checkout@v3
      with:
        repository: wenfxl/KuaiYanWeb   # 你的前端 fork 仓库
        path: KuaiYanWeb                # checkout 到这个子目录

    # 安装 Node.js 构建前端
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build Frontend
      working-directory: KuaiYanWeb
      run: |
        npm install
        npm run build

    # 安装 Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    # 编译 Go 后端，embed 前端 dist
    - name: Build Go Backend
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o KuaiYanGo2.bin main.go

    # 上传生成的 bin（使用最新 v4 版本）
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: KuaiYanGo2-bin
        path: KuaiYanGo2.bin
